#!/usr/bin/env bash
# shellcheck disable=SC2016 # Migration entries intentionally match literal Zsh expressions.
set -e

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
zshenv_file="$HOME/.zshenv"
zshrc_file="$HOME/.zshrc"
managed_start="# >>> clouddots >>>"
managed_end="# <<< clouddots <<<"
codespace_start="# >>> codespace-env >>>"
codespace_end="# <<< codespace-env <<<"

mkdir -p "$HOME/.local/share/zsh"

cp -f "$script_dir/p10k.zsh" "$HOME/.p10k.zsh"
cp -f "$script_dir/.zsh_plugins.txt" "$HOME/.zsh_plugins.txt"
touch "$zshenv_file" "$zshrc_file"

remove_block() {
  local target_file="$1"
  local start_marker="$2"
  local end_marker="$3"
  local temp_file="${target_file}.tmp.$$"

  awk -v start="$start_marker" -v end="$end_marker" '
    $0 == start { skip=1; next }
    $0 == end { skip=0; next }
    !skip
  ' "$target_file" > "$temp_file"
  mv "$temp_file" "$target_file"
}

remove_block "$zshenv_file" "$managed_start" "$managed_end"
remove_block "$zshenv_file" "$codespace_start" "$codespace_end"
remove_block "$zshrc_file" "$managed_start" "$managed_end"

# Remove entries generated by older clouddots versions.
sed -i.bak \
  -e '/^export PATH=.*fnm.*npm-global.*cargo/d' \
  -e '/^export SHELL=/d' \
  -e '/^export EDITOR=nvim$/d' \
  -e '/^export COPILOT_HOOK_ALLOW_LOCALHOST=1$/d' \
  -e '/^export BASH_ENV=/d' \
  -e '/^WORDCHARS=/d' \
  -e '/^\[\[ -n "\$SSH_CONNECTION\$SSH_CLIENT\$SSH_TTY\$DEVPOD\$REMOTE_CONTAINERS" \]\].*BROWSER=/d' \
  "$zshenv_file"
rm -f "${zshenv_file}.bak"

legacy_zshrc_entries=(
  'setopt HIST_IGNORE_SPACE'
  'autoload -Uz promptinit && promptinit && prompt powerlevel10k'
  'antidote load'
  '! (( $+functions[antidote] )) && source "$HOME/.antidote/antidote.zsh"'
  '[[ ! -d "$HOME/.antidote" ]] && git clone --depth=1 https://github.com/mattmc3/antidote.git "$HOME/.antidote"'
  'ZSH_AUTOSUGGEST_STRATEGY=(history completion)'
  '[[ -x /home/linuxbrew/.linuxbrew/bin/brew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  '[[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"'
  '(( $+commands[fnm] )) && eval "$(fnm env --use-on-cd --shell zsh)"'
  '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh'
  '(( $+commands[nvim] )) && alias vi=nvim'
  '(( $+commands[nvim] )) && alias vim=nvim'
  'alias l="ls -lah"'
  '[[ $- == *i* && -t 0 ]] && stty -ixon'
  '[[ -f "$HOME/notification-sender.sh" ]] && source "$HOME/notification-sender.sh"'
  "zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'"
  "zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'"
  "zstyle ':autocomplete:*' insert-unambiguous yes"
  "zstyle ':autocomplete:*' widget-style menu-select"
  "zstyle ':autocomplete:*' fzf-completion yes"
  "zstyle ':completion:*' group-name ''"
  "zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'"
  "zstyle ':completion:*:messages' format '%F{purple}-- %d --%f'"
  "zstyle ':completion:*:warnings' format '%F{red}-- no matches found --%f'"
  "zstyle ':completion:*' list-colors \${(s.:.)LS_COLORS}"
  "zstyle ':omz:plugins:eza' 'icons' yes"
  "bindkey -M viins '^[^?' backward-kill-word # Alt+Backspace"
  "bindkey -M viins '^[d' kill-word           # Alt+D"
  "bindkey -M viins '^[[1;3D' backward-word   # Alt+Left"
  "bindkey -M viins '^[[1;3C' forward-word    # Alt+Right"
  "bindkey -M viins '^[b' backward-word       # Alt+B"
  "bindkey -M viins '^[f' forward-word        # Alt+F"
  "bindkey '^[[C' forward-char"
)
for entry in "${legacy_zshrc_entries[@]}"; do
  grep -Fxv "$entry" "$zshrc_file" > "${zshrc_file}.tmp.$$" || true
  mv "${zshrc_file}.tmp.$$" "$zshrc_file"
done

sed -i.bak \
  -e '/# Enable Powerlevel10k instant prompt/,/^fi$/d' \
  -e '/^source \$ZSH\/oh-my-zsh.sh/s/^/# /' \
  -e '/^plugins=/s/^/# /' \
  -e '/^ZSH_THEME=/s/^/# /' \
  -e '/^export ZSH=/s/^/# /' \
  "$zshrc_file"
rm -f "${zshrc_file}.bak"

cat >> "$zshenv_file" <<'ZSHENV'
# >>> clouddots >>>
export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-$EDITOR}"
export COPILOT_HOOK_ALLOW_LOCALHOST=1
export BASH_ENV="${BASH_ENV:-$HOME/.bashenv}"
export SHELL="${commands[zsh]:-/bin/zsh}"

if [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

typeset -U path PATH
path=(
  "$HOME/.local/bin"
  "$HOME/.local/share/fnm"
  "$HOME/.npm-global/bin"
  "$HOME/.cargo/bin"
  "$HOME/go/bin"
  "$HOME/.bun/bin"
  /home/linuxbrew/.linuxbrew/bin
  /home/linuxbrew/.linuxbrew/sbin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/local/bin
  /usr/local/sbin
  $path
)

if [[ ! -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]] && (( $+commands[fnm] )); then
  if [[ -o interactive ]]; then
    eval "$(fnm env --use-on-cd --shell zsh)"
  else
    eval "$(fnm env --shell zsh)"
  fi
fi

[[ -n "$SSH_CONNECTION$SSH_CLIENT$SSH_TTY$DEVPOD$REMOTE_CONTAINERS" ]] &&
  export BROWSER="$HOME/browser-opener.sh"

# >>> codespace-env >>>
if [[ -n "$SSH_CONNECTION" && -f /workspaces/.codespaces/shared/.env-secrets ]]; then
  while IFS= read -r line; do
    key="${line%%=*}"
    value="${line#*=}"
    decoded_value="$(printf '%s' "$value" | base64 -d 2>/dev/null)" || continue
    if [[ "$key" == "PATH" ]]; then
      IFS=: read -rA env_paths <<< "$decoded_value"
      for p in "${env_paths[@]}"; do
        [[ -n "$p" && ":$PATH:" != *":$p:"* ]] && path+=("$p")
      done
    else
      export "$key=$decoded_value"
    fi
  done < /workspaces/.codespaces/shared/.env-secrets
fi
# <<< codespace-env <<<
# <<< clouddots <<<
ZSHENV

if [[ -d "$HOME/.antidote/.git" ]]; then
  git -C "$HOME/.antidote" pull --ff-only
else
  git clone --depth=1 https://github.com/mattmc3/antidote.git "$HOME/.antidote"
fi

plugins_tmp="$HOME/.zsh_plugins.zsh.tmp.$$"
if ZDOTDIR="$HOME" zsh -c '
  source "$HOME/.antidote/antidote.zsh"
  zstyle ":antidote:bundle:*" defer-options "-m"
  antidote bundle < "$HOME/.zsh_plugins.txt" > "$1"
' zsh "$plugins_tmp"; then
  mv "$plugins_tmp" "$HOME/.zsh_plugins.zsh"
else
  rm -f "$plugins_tmp"
  exit 1
fi

zshrc_tmp="${zshrc_file}.tmp.$$"
cat > "$zshrc_tmp" <<'ZSHRC'
# >>> clouddots >>>
# Enable Powerlevel10k instant prompt. Keep this close to the top.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt HIST_IGNORE_SPACE
zstyle ':antidote:bundle:*' defer-options '-m'
[[ -r "$HOME/.antidote/antidote.zsh" ]] && source "$HOME/.antidote/antidote.zsh"
[[ -r "$HOME/.zsh_plugins.zsh" ]] && source "$HOME/.zsh_plugins.zsh"
zstyle ':completion:*' matcher-list \
  'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' \
  'r:|[._-]=* r:|=*' \
  'l:|=* r:|=*'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format '%F{purple}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{red}-- no matches found --%f'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':autocomplete:*' insert-unambiguous yes
zstyle ':autocomplete:*' widget-style menu-select
zstyle ':autocomplete:*' fzf-completion yes
zstyle ':omz:plugins:eza' icons yes

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZFUNCDIR="$HOME/.config/zsh/functions"

alias l='ls -lah'
if (( $+commands[nvim] )); then
  alias vi='nvim'
  alias vim='nvim'
fi

[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"
[[ $- == *i* && -t 0 ]] && stty -ixon
[[ -f "$HOME/notification-sender.sh" ]] && source "$HOME/notification-sender.sh"
# <<< clouddots <<<
ZSHRC
cat "$zshrc_file" >> "$zshrc_tmp"
mv "$zshrc_tmp" "$zshrc_file"
