#!/usr/bin/env bash
# shellcheck disable=SC2016 # Managed blocks intentionally contain literal shell expressions.
set -e

bashenv_file="$HOME/.bashenv"
bashrc_file="$HOME/.bashrc"
managed_start="# >>> clouddots >>>"
managed_end="# <<< clouddots <<<"
codespace_start="# >>> codespace-env >>>"
codespace_end="# <<< codespace-env <<<"

touch "$bashenv_file" "$bashrc_file"

remove_block() {
  local target_file="$1"
  local start_marker="$2"
  local end_marker="$3"
  local temp_file="${target_file}.tmp.$$"

  awk -v start="$start_marker" -v end="$end_marker" '
    $0 == start { skip=1; next }
    $0 == end { skip=0; next }
    !skip
  ' "$target_file" > "$temp_file"
  mv "$temp_file" "$target_file"
}

for target_file in "$bashenv_file" "$bashrc_file"; do
  remove_block "$target_file" "$managed_start" "$managed_end"
  remove_block "$target_file" "$codespace_start" "$codespace_end"

  legacy_az_function='az() { AZURE_DEVOPS_EXT_PAT=$(ado-auth-helper get-access-token) command az "$@"; }'
  grep -Fxv "$legacy_az_function" "$target_file" > "${target_file}.tmp.$$" || true
  mv "${target_file}.tmp.$$" "$target_file"
done

# Remove entries generated by older clouddots versions.
sed -i.bak \
  -e '/^export EDITOR=nvim$/d' \
  -e '/^export COPILOT_HOOK_ALLOW_LOCALHOST=1$/d' \
  -e '/^\[\[ -d "\$HOME\/.local\/bin" && .*export PATH=/d' \
  "$bashenv_file"
rm -f "${bashenv_file}.bak"

sed -i.bak \
  -e '/^export PATH=.*linuxbrew.*fnm.*npm-global.*cargo/d' \
  -e '/^export SHELL=.*bash/d' \
  -e '/^export EDITOR=nvim$/d' \
  -e '/^export COPILOT_HOOK_ALLOW_LOCALHOST=1$/d' \
  -e '/^export BASH_ENV=/d' \
  -e '/^\[\[ -n "\$SSH_CONNECTION\$SSH_CLIENT\$SSH_TTY\$DEVPOD\$REMOTE_CONTAINERS" \]\].*BROWSER=/d' \
  -e '/^\[\[ -x \/home\/linuxbrew\/.linuxbrew\/bin\/brew \]\].*shellenv/d' \
  -e '/^\[\[ -d "\$HOME\/.local\/bin" \]\].*PATH=/d' \
  -e '/^command -v fnm .*fnm env --use-on-cd --shell bash/d' \
  -e '/^\[ -f "\$HOME\/notification-sender.sh" \] && source "\$HOME\/notification-sender.sh"$/d' \
  -e '/^source "\$HOME\/notification-sender.sh"$/d' \
  -e '/^\. "\$HOME\/notification-sender.sh"$/d' \
  "$bashrc_file"
rm -f "${bashrc_file}.bak"

cat >> "$bashenv_file" <<'BASHENV'
# >>> clouddots >>>
export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-$EDITOR}"
export COPILOT_HOOK_ALLOW_LOCALHOST=1
export BASH_ENV="${BASH_ENV:-$HOME/.bashenv}"
export SHELL="$(command -v bash)"

for path_entry in \
  "/usr/local/sbin" \
  "/usr/local/bin" \
  "/opt/homebrew/sbin" \
  "/opt/homebrew/bin" \
  "/home/linuxbrew/.linuxbrew/sbin" \
  "/home/linuxbrew/.linuxbrew/bin" \
  "$HOME/.bun/bin" \
  "$HOME/go/bin" \
  "$HOME/.cargo/bin" \
  "$HOME/.npm-global/bin" \
  "$HOME/.local/share/fnm" \
  "$HOME/.local/bin"
do
  if [[ -d "$path_entry" && ":$PATH:" != *":$path_entry:"* ]]; then
    PATH="$path_entry:$PATH"
  fi
done
export PATH
unset path_entry

if [[ ! -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]] &&
  command -v fnm >/dev/null 2>&1; then
  if [[ $- == *i* ]]; then
    eval "$(fnm env --use-on-cd --shell bash)"
  else
    eval "$(fnm env --shell bash)"
  fi
fi

[[ -n "$SSH_CONNECTION$SSH_CLIENT$SSH_TTY$DEVPOD$REMOTE_CONTAINERS" ]] &&
  export BROWSER="$HOME/browser-opener.sh"

# >>> codespace-env >>>
if [[ -n "$SSH_CONNECTION" && -f /workspaces/.codespaces/shared/.env-secrets ]]; then
  while IFS= read -r line; do
    key="${line%%=*}"
    value="${line#*=}"
    decoded_value="$(printf '%s' "$value" | base64 -d 2>/dev/null)" || continue
    if [[ "$key" == "PATH" ]]; then
      IFS=: read -ra env_paths <<< "$decoded_value"
      for p in "${env_paths[@]}"; do
        [[ -n "$p" && ":$PATH:" != *":$p:"* ]] && PATH="$PATH:$p"
      done
      export PATH
    else
      export "$key=$decoded_value"
    fi
  done < /workspaces/.codespaces/shared/.env-secrets
fi
# <<< codespace-env <<<
# <<< clouddots <<<
BASHENV

bashrc_tmp="${bashrc_file}.tmp.$$"
cat > "$bashrc_tmp" <<'BASHRC'
# >>> clouddots >>>
[[ -r "$HOME/.bashenv" ]] && source "$HOME/.bashenv"

if [[ $- == *i* ]]; then
  alias l='ls -lah'
  if command -v nvim >/dev/null 2>&1; then
    alias vi='nvim'
    alias vim='nvim'
  fi

  [[ -f "$HOME/notification-sender.sh" ]] && source "$HOME/notification-sender.sh"
fi
# <<< clouddots <<<
BASHRC
cat "$bashrc_file" >> "$bashrc_tmp"
mv "$bashrc_tmp" "$bashrc_file"

profile_entry='[[ -r "$HOME/.bashrc" ]] && source "$HOME/.bashrc"'
touch "$HOME/.bash_profile"
grep -Fxq "$profile_entry" "$HOME/.bash_profile" ||
  printf '\n%s\n' "$profile_entry" >> "$HOME/.bash_profile"
