#!/bin/env fish

set -Ux _tide_left_items pwd\x1egit\x1enewline\x1echaracter
set -Ux _tide_prompt_36383 \x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x40PWD\x40\x1b\x5b38\x3b2\x3b148\x3b148\x3b148m\x20\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x5b37m\x1b\x5b38\x3b2\x3b95\x3b215\x3b0mmaster\x1b\x5b38\x3b2\x3b255\x3b0\x3b0m\x1b\x5b38\x3b2\x3b95\x3b215\x3b0m\x20\u21e32\x1b\x5b38\x3b2\x3b95\x3b215\x3b0m\x1b\x5b38\x3b2\x3b255\x3b0\x3b0m\x1b\x5b38\x3b2\x3b215\x3b175\x3b0m\x1b\x5b38\x3b2\x3b215\x3b175\x3b0m\x1b\x5b38\x3b2\x3b0\x3b175\x3b255m\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x20\x1e\x1b\x5b38\x3b2\x3b95\x3b215\x3b0m\u276f\x1e\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x20\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x5b38\x3b2\x3b68\x3b136\x3b62m\ue24f\x2020\x2e17\x2e0\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm
set -Ux _tide_prompt_38281 \x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x5b34m\ue0b6\x1b\x5b44m\x40PWD\x40\x1b\x28B\x1b\x5bm\x1b\x28B\x1b\x5bm\x1b\x5b34m\ue0b0\x1e\x1b\x5b92m\u276f
set -Ux _tide_right_items status\x1ecmd_duration\x1econtext\x1ejobs\x1enode\x1epython
set -Ux tide_aws_bg_color yellow
set -Ux tide_aws_color brblack
set -Ux tide_aws_icon \uf270
set -Ux tide_character_color brgreen
set -Ux tide_character_color_failure brred
set -Ux tide_character_icon \u276f
set -Ux tide_character_vi_icon_default \u276e
set -Ux tide_character_vi_icon_replace \u25b6
set -Ux tide_character_vi_icon_visual V
set -Ux tide_cmd_duration_bg_color yellow
set -Ux tide_cmd_duration_color black
set -Ux tide_cmd_duration_decimals 0
set -Ux tide_cmd_duration_icon \uf252
set -Ux tide_cmd_duration_threshold 3000
set -Ux tide_context_always_display false
set -Ux tide_context_bg_color brblack
set -Ux tide_context_color_default yellow
set -Ux tide_context_color_root yellow
set -Ux tide_context_color_ssh yellow
set -Ux tide_context_hostname_parts 1
set -Ux tide_crystal_bg_color brwhite
set -Ux tide_crystal_color black
set -Ux tide_crystal_icon \ue62f
set -Ux tide_direnv_bg_color bryellow
set -Ux tide_direnv_bg_color_denied brred
set -Ux tide_direnv_color black
set -Ux tide_direnv_color_denied black
set -Ux tide_direnv_icon \u25bc
set -Ux tide_distrobox_bg_color brmagenta
set -Ux tide_distrobox_color black
set -Ux tide_distrobox_icon \U000f01a7
set -Ux tide_docker_bg_color blue
set -Ux tide_docker_color black
set -Ux tide_docker_default_contexts default\x1ecolima
set -Ux tide_docker_icon \uf308
set -Ux tide_elixir_bg_color magenta
set -Ux tide_elixir_color black
set -Ux tide_elixir_icon \ue62d
set -Ux tide_gcloud_bg_color blue
set -Ux tide_gcloud_color black
set -Ux tide_gcloud_icon \U000f02ad
set -Ux tide_git_bg_color green
set -Ux tide_git_bg_color_unstable yellow
set -Ux tide_git_bg_color_urgent red
set -Ux tide_git_color_branch black
set -Ux tide_git_color_conflicted black
set -Ux tide_git_color_dirty black
set -Ux tide_git_color_operation black
set -Ux tide_git_color_staged black
set -Ux tide_git_color_stash black
set -Ux tide_git_color_untracked black
set -Ux tide_git_color_upstream black
set -Ux tide_git_icon \ue702
set -Ux tide_git_truncation_length 24
set -Ux tide_git_truncation_strategy \x1d
set -Ux tide_go_bg_color brcyan
set -Ux tide_go_color black
set -Ux tide_go_icon \ue627
set -Ux tide_java_bg_color yellow
set -Ux tide_java_color black
set -Ux tide_java_icon \ue256
set -Ux tide_jobs_bg_color brblack
set -Ux tide_jobs_color green
set -Ux tide_jobs_icon \uf013
set -Ux tide_jobs_number_threshold 1000
set -Ux tide_kubectl_bg_color blue
set -Ux tide_kubectl_color black
set -Ux tide_kubectl_icon \U000f10fe
set -Ux tide_left_prompt_frame_enabled true
set -Ux tide_left_prompt_items os\x1epwd\x1egit\x1enewline\x1echaracter
set -Ux tide_left_prompt_prefix \ue0b6
set -Ux tide_left_prompt_separator_diff_color \ue0b0
set -Ux tide_left_prompt_separator_same_color \ue0b1
set -Ux tide_left_prompt_suffix \ue0b0
set -Ux tide_nix_shell_bg_color brblue
set -Ux tide_nix_shell_color black
set -Ux tide_nix_shell_icon \uf313
set -Ux tide_node_bg_color green
set -Ux tide_node_color black
set -Ux tide_node_icon \ue24f
set -Ux tide_os_bg_color white
set -Ux tide_os_color black
set -Ux tide_os_icon \uf31b
set -Ux tide_php_bg_color blue
set -Ux tide_php_color black
set -Ux tide_php_icon \ue608
set -Ux tide_private_mode_bg_color brwhite
set -Ux tide_private_mode_color black
set -Ux tide_private_mode_icon \U000f05f9
set -Ux tide_prompt_add_newline_before false
set -Ux tide_prompt_color_frame_and_connection brblack
set -Ux tide_prompt_color_separator_same_color brblack
set -Ux tide_prompt_icon_connection \x20
set -Ux tide_prompt_min_cols 34
set -Ux tide_prompt_pad_items true
set -Ux tide_prompt_transient_enabled true
set -Ux tide_pulumi_bg_color yellow
set -Ux tide_pulumi_color black
set -Ux tide_pulumi_icon \uf1b2
set -Ux tide_pwd_bg_color blue
set -Ux tide_pwd_color_anchors brwhite
set -Ux tide_pwd_color_dirs brwhite
set -Ux tide_pwd_color_truncated_dirs white
set -Ux tide_pwd_icon \uf07c
set -Ux tide_pwd_icon_home \uf015
set -Ux tide_pwd_icon_unwritable \uf023
set -Ux tide_pwd_markers \x2ebzr\x1e\x2ecitc\x1e\x2egit\x1e\x2ehg\x1e\x2enode\x2dversion\x1e\x2epython\x2dversion\x1e\x2eruby\x2dversion\x1e\x2eshorten_folder_marker\x1e\x2esvn\x1e\x2eterraform\x1eCargo\x2etoml\x1ecomposer\x2ejson\x1eCVS\x1ego\x2emod\x1epackage\x2ejson\x1ebuild\x2ezig
set -Ux tide_python_bg_color brblack
set -Ux tide_python_color cyan
set -Ux tide_python_icon \U000f0320
set -Ux tide_right_prompt_frame_enabled false
set -Ux tide_right_prompt_items status\x1ecmd_duration\x1econtext\x1ejobs\x1edirenv\x1enode\x1epython\x1erustc\x1ejava\x1ephp\x1epulumi\x1eruby\x1ego\x1egcloud\x1ekubectl\x1edistrobox\x1etoolbox\x1eterraform\x1eaws\x1enix_shell\x1ecrystal\x1eelixir\x1ezig\x1etime
set -Ux tide_right_prompt_prefix \u2591\u2592\u2593
set -Ux tide_right_prompt_separator_diff_color \ue0b2
set -Ux tide_right_prompt_separator_same_color \ue0b3
set -Ux tide_right_prompt_suffix \u2593\u2592\u2591
set -Ux tide_ruby_bg_color red
set -Ux tide_ruby_color black
set -Ux tide_ruby_icon \ue23e
set -Ux tide_rustc_bg_color red
set -Ux tide_rustc_color black
set -Ux tide_rustc_icon \ue7a8
set -Ux tide_shlvl_bg_color yellow
set -Ux tide_shlvl_color black
set -Ux tide_shlvl_icon \uf120
set -Ux tide_shlvl_threshold 1
set -Ux tide_status_bg_color black
set -Ux tide_status_bg_color_failure red
set -Ux tide_status_color green
set -Ux tide_status_color_failure bryellow
set -Ux tide_status_icon \u2714
set -Ux tide_status_icon_failure \u2718
set -Ux tide_terraform_bg_color magenta
set -Ux tide_terraform_color black
set -Ux tide_terraform_icon \U000f1062
set -Ux tide_time_bg_color white
set -Ux tide_time_color black
set -Ux tide_time_format \x25T
set -Ux tide_toolbox_bg_color magenta
set -Ux tide_toolbox_color black
set -Ux tide_toolbox_icon \ue24f
set -Ux tide_vi_mode_bg_color_default white
set -Ux tide_vi_mode_bg_color_insert cyan
set -Ux tide_vi_mode_bg_color_replace green
set -Ux tide_vi_mode_bg_color_visual yellow
set -Ux tide_vi_mode_color_default black
set -Ux tide_vi_mode_color_insert black
set -Ux tide_vi_mode_color_replace black
set -Ux tide_vi_mode_color_visual black
set -Ux tide_vi_mode_icon_default D
set -Ux tide_vi_mode_icon_insert I
set -Ux tide_vi_mode_icon_replace R
set -Ux tide_vi_mode_icon_visual V
set -Ux tide_zig_bg_color yellow
set -Ux tide_zig_color black
set -Ux tide_zig_icon \ue6a9
