set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u
set -g escape-time 10
set -g focus-events on
set -g bell-action any
set -g monitor-activity on
set -g set-clipboard on
set -g allow-passthrough on
set -ga terminal-features ',*:RGB'
set -g default-terminal "tmux-256color"
set -g set-titles on
set -g set-titles-string '🐚 #W: #T'
set -g allow-rename on
set -ga update-environment ' CODESPACE_NAME CODESPACE_VSCODE_FOLDER VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_EXTRA_ARGS VSCODE_GIT_ASKPASS_MAIN VSCODE_GIT_IPC_HANDLE VSCODE_IPC_HOOK_CLI VSCODE_INJECTION VSCODE_NONCE'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'
